/**
 * 300 of the most-used positive affirmations, grouped by life area
 * (health, wealth, happiness, confidence, career, relationships, gratitude,
 * peace, growth, self-love). All first-person, present-tense. Picked at random
 * client-side — no API, no CORS, works offline.
 */
export const AFFIRMATIONS: string[] = [
  // ── Health ──────────────────────────────────────────────
  'My body is strong, healthy, and full of energy.',
  'I nourish myself with food that heals and fuels me.',
  'Every day my health improves in every way.',
  'I listen to my body and give it the rest it needs.',
  'I am grateful for a body that carries me through life.',
  'My mind and body are in perfect balance.',
  'I breathe deeply and fill myself with calm energy.',
  'I move my body with joy and gratitude.',
  'Healing flows through every cell of my body.',
  'I choose habits that support my long-term health.',
  'I sleep deeply and wake up refreshed.',
  'My immune system is strong and protects me.',
  'I treat my body with kindness and respect.',
  'I have the energy to do everything I love.',
  'Each breath fills me with vitality.',
  'I release tension and welcome relaxation.',
  'I am committed to my physical and mental wellbeing.',
  'My body knows how to heal itself.',
  'I drink water and feel refreshed and alive.',
  'I am getting stronger and healthier every day.',
  'I honor my body by moving it daily.',
  'Good health is my natural state.',
  'I let go of stress and embrace peace.',
  'My energy is vibrant and contagious.',
  'I make time to care for myself.',
  'I feel light, free, and full of life.',
  'My body deserves love and good care.',
  'I am at peace with my body exactly as it is.',
  'Wellness is a journey I enjoy every day.',
  'I radiate health from the inside out.',

  // ── Wealth ──────────────────────────────────────────────
  'Money flows to me easily and abundantly.',
  'I am worthy of financial abundance.',
  'I attract wealth and opportunities effortlessly.',
  'My income grows every single day.',
  'I manage my money wisely and confidently.',
  'Abundance is my natural state of being.',
  'I am open to receiving wealth from many sources.',
  'Every dollar I spend returns to me multiplied.',
  'I deserve to be financially free.',
  'I create value and am rewarded generously.',
  'My finances improve beyond my expectations.',
  'I am a magnet for money and prosperity.',
  'Wealth comes to me in expected and unexpected ways.',
  'I release all fear around money.',
  'I have more than enough to share and to save.',
  'Financial success comes naturally to me.',
  'I think and act from a mindset of abundance.',
  'I am grateful for the money I have and the money on its way.',
  'Prosperity surrounds me wherever I go.',
  'I make smart decisions that grow my wealth.',
  'My savings grow steadily and securely.',
  'I am building lasting financial security.',
  'Opportunities to prosper are everywhere.',
  'I welcome abundance into every area of my life.',
  'I am capable of achieving financial freedom.',
  'Money is a tool I use to create a great life.',
  'I deserve to be paid well for my work.',
  'Wealth and generosity flow through me.',
  'I attract clients, income, and opportunity.',
  'My relationship with money is healthy and positive.',

  // ── Happiness ───────────────────────────────────────────
  'I choose joy in this moment.',
  'Happiness is a choice I make every day.',
  'I find delight in the little things.',
  'My heart is full of gratitude and joy.',
  'I deserve to be happy.',
  'I create my own sunshine.',
  'Joy flows through me effortlessly.',
  'I smile easily and laugh often.',
  'I focus on what brings me happiness.',
  'Every day brings new reasons to smile.',
  'I am the source of my own happiness.',
  'I let go of what no longer serves my joy.',
  'I am surrounded by positivity and light.',
  'My happiness inspires those around me.',
  'I choose to see the good in every situation.',
  'Contentment lives within me.',
  'I celebrate the joy in ordinary moments.',
  'I am grateful for this beautiful life.',
  'Peace and happiness are my birthright.',
  'I welcome happiness with open arms.',
  'My life is filled with moments of joy.',
  'I deserve a life that feels good.',
  'I radiate positive energy.',
  'Happiness follows me wherever I go.',
  'I find joy in being exactly who I am.',
  'Today is full of possibility and delight.',
  'I choose thoughts that make me happy.',
  'My joy does not depend on others.',
  'I am at peace and full of joy.',
  'I am thankful for another wonderful day.',

  // ── Confidence ──────────────────────────────────────────
  'I believe in myself and my abilities.',
  'I am confident, capable, and strong.',
  'I trust my decisions completely.',
  'I am worthy of respect and admiration.',
  'I speak with confidence and clarity.',
  'I am enough exactly as I am.',
  'I stand tall and own my power.',
  'Fear does not control me.',
  'I face challenges with courage.',
  'I am proud of who I am becoming.',
  'My confidence grows stronger every day.',
  'I have everything I need to succeed.',
  'I trust myself to handle whatever comes.',
  'I am brave and bold.',
  'I deserve to take up space.',
  'My voice matters and deserves to be heard.',
  'I let go of self-doubt.',
  'I am comfortable being myself.',
  'I am capable of achieving anything I set my mind to.',
  'I radiate confidence and self-assurance.',
  'I embrace my strengths and accept my flaws.',
  'I am unstoppable when I believe in myself.',
  'I trust the process of my life.',
  'I am secure in who I am.',
  'I deserve all the good things coming to me.',
  'I act with courage and conviction.',
  'Challenges make me stronger and wiser.',
  'I am the author of my own story.',
  'I rise above doubt and fear.',
  'My potential is limitless.',

  // ── Career & Success ────────────────────────────────────
  'I am successful in everything I do.',
  'I attract opportunities that align with my goals.',
  'My work makes a meaningful difference.',
  'I am focused, productive, and driven.',
  'Success comes naturally to me.',
  'I turn my dreams into reality.',
  'I am proud of the work I create.',
  'Every step I take moves me closer to my goals.',
  'I am capable of achieving great things.',
  'I learn and grow from every experience.',
  'My career is thriving and fulfilling.',
  'I am recognized and rewarded for my talents.',
  'I work with passion and purpose.',
  'Opportunities find me with ease.',
  'I am a leader and an inspiration.',
  'I set goals and achieve them.',
  'I am disciplined and motivated.',
  'My ideas are valuable and impactful.',
  'I create success on my own terms.',
  'I am building the future I dream of.',
  'I overcome obstacles with creativity.',
  'I am exactly where I need to be in my journey.',
  'My hard work pays off.',
  'I deserve success and abundance.',
  'I am growing into the best version of myself.',
  'I welcome challenges as chances to grow.',
  'My focus creates powerful results.',
  'I am confident in my skills and talents.',
  'Success flows to me effortlessly.',
  'I am committed to my growth and goals.',

  // ── Relationships & Love ────────────────────────────────
  'I am surrounded by loving, supportive people.',
  'I attract healthy and loving relationships.',
  'I give and receive love freely.',
  'I am worthy of deep, genuine love.',
  'My relationships are built on trust and respect.',
  'I communicate with honesty and kindness.',
  'I am a loving and caring person.',
  'I deserve to be treated with kindness.',
  'Love flows into my life abundantly.',
  'I nurture the relationships that matter most.',
  'I am open to giving and receiving love.',
  'I forgive easily and let go of resentment.',
  'My heart is open and full of compassion.',
  'I attract people who appreciate and respect me.',
  'I am grateful for the love in my life.',
  'I create deep and meaningful connections.',
  'I am loved for exactly who I am.',
  'I bring warmth and joy to those around me.',
  'I choose relationships that lift me up.',
  'I am surrounded by positive, caring energy.',
  'I deserve healthy and happy relationships.',
  'Loving myself lets me truly love others.',
  'I attract kindness and return it generously.',
  'My connections grow stronger every day.',
  'I am a source of love and support.',
  'I release relationships that no longer serve me.',
  'I am patient and understanding with others.',
  'Love begins with how I treat myself.',
  'I welcome new and meaningful friendships.',
  'I am grateful for everyone who walks with me.',

  // ── Gratitude ───────────────────────────────────────────
  'I am grateful for everything I have.',
  'Gratitude fills my heart each morning.',
  'I appreciate the beauty around me.',
  'I give thanks for the small joys of life.',
  'I am thankful for the people in my life.',
  'Every day brings something to be grateful for.',
  'I focus on abundance, not lack.',
  'I am blessed beyond measure.',
  'Gratitude turns what I have into enough.',
  'I appreciate this moment exactly as it is.',
  'I am thankful for my health and strength.',
  "I notice and cherish life's gifts.",
  'My heart overflows with appreciation.',
  'I am grateful for new opportunities each day.',
  'Thankfulness brings me peace and joy.',
  'I appreciate how far I have come.',
  'I am grateful for the lessons I learn.',
  'I find something to be thankful for in every day.',
  'Gratitude is my natural way of being.',
  'I am thankful for my journey, past and present.',
  'I appreciate myself and all I do.',
  'I give thanks for the love that surrounds me.',
  'I am grateful for the present moment.',
  'Appreciation opens my heart to more abundance.',
  'I count my blessings every single day.',
  'I am thankful for the simple pleasures of life.',
  'Gratitude grounds me and lifts me up.',
  'I welcome each day with a thankful heart.',
  'I am grateful for who I am becoming.',
  'A thankful heart is my greatest strength.',

  // ── Peace & Calm ────────────────────────────────────────
  'I am calm, centered, and at peace.',
  'I release all tension and stress.',
  'Peace flows through me with every breath.',
  'I let go of what I cannot control.',
  'My mind is calm and quiet.',
  'I choose serenity over worry.',
  'I am safe and at ease.',
  'I breathe in calm and breathe out stress.',
  'Stillness restores my energy.',
  'I am grounded and present.',
  'I trust that everything is unfolding as it should.',
  'I create a peaceful space within me.',
  'My thoughts are gentle and kind.',
  'I am free from anxiety and fear.',
  'Tranquility surrounds me.',
  'I allow myself to slow down and rest.',
  'I find peace in the present moment.',
  'I am in harmony with myself and the world.',
  'Calmness is my natural state.',
  'I let peace guide my actions.',
  'I release the need to rush.',
  'My heart is steady and serene.',
  'I welcome quiet and stillness.',
  'I am patient with myself and others.',
  'Peace begins within me.',
  'I let go of yesterday and tomorrow.',
  'I rest in the calm of this moment.',
  'My breath anchors me in peace.',
  'I am surrounded by calming energy.',
  'I choose peace, again and again.',

  // ── Growth & Resilience ─────────────────────────────────
  'I grow stronger with every challenge.',
  'I learn something valuable from every setback.',
  'I am constantly evolving and improving.',
  'I embrace change as an opportunity.',
  'I am resilient and bounce back quickly.',
  'Every experience helps me grow.',
  'I am becoming a better version of myself.',
  'I rise above obstacles with determination.',
  'Mistakes are lessons that help me grow.',
  'I am open to new ideas and possibilities.',
  'I adapt easily to whatever life brings.',
  'My potential expands every day.',
  'I turn challenges into stepping stones.',
  'I am brave enough to start over.',
  'Growth happens outside my comfort zone.',
  'I trust my ability to figure things out.',
  'I am stronger than any challenge I face.',
  'I welcome growth, even when it is hard.',
  'Setbacks are setups for comebacks.',
  'I keep going, no matter what.',
  'I learn, adapt, and overcome.',
  'Every day I become wiser and stronger.',
  'I am capable of incredible growth.',
  'I face the unknown with courage.',
  'I am proud of how far I have come.',
  'Progress, not perfection, is my goal.',
  'I grow through what I go through.',
  'I am resilient in the face of adversity.',
  'Challenges reveal my inner strength.',
  'I am always moving forward.',

  // ── Self-Love ───────────────────────────────────────────
  'I love and accept myself completely.',
  'I am enough, just as I am.',
  'I treat myself with kindness and compassion.',
  'I deserve love, especially from myself.',
  'I am proud of the person I am.',
  'I forgive myself for past mistakes.',
  'I honor my needs and feelings.',
  'I am worthy of all good things.',
  'I speak to myself with gentleness.',
  'I celebrate my unique qualities.',
  'I am my own best friend.',
  'I deserve rest, joy, and care.',
  'I accept myself unconditionally.',
  'I am comfortable in my own skin.',
  'I let go of comparison and embrace my path.',
  'I am allowed to put myself first.',
  'My worth is not defined by others.',
  'I nurture my mind, body, and soul.',
  'I am beautiful inside and out.',
  'I give myself permission to shine.',
  'I release self-criticism and choose self-love.',
  'I am deserving of happiness and peace.',
  'I honor my journey and my pace.',
  'I am kind to myself in every moment.',
  'I appreciate everything that makes me, me.',
  'I am whole and complete on my own.',
  'I choose to believe in myself.',
  'I deserve to take up space and be seen.',
  'My relationship with myself is loving and strong.',
  'I am exactly who I am meant to be.',
]
