/**
 * Affirmations grounded in Stoic philosophy (Marcus Aurelius, Epictetus, Seneca),
 * psychology (Frankl, Dweck, Seligman), and practical wisdom. First-person, present-tense.
 */
export const AFFIRMATIONS: string[] = [

  // ── Stoic: Control & Acceptance ─────────────────────────
  'I focus only on what is within my control and release the rest.',
  'My judgement of events shapes my experience far more than the events themselves.',
  'I meet obstacles with reason, not reaction.',
  'What happens to me is not in my power; how I respond always is.',
  'I distinguish clearly between what I can change and what I must accept.',
  'I do not need external things to go well in order to be well inside.',
  'This moment, however difficult, is exactly what I need to practice virtue.',
  'I refuse to give power over my mind to things that cannot think.',
  'Adversity is the material I use to build character.',
  'I am not disturbed by things, only by my opinions about things.',
  'I can endure what I must and let go of what I cannot change.',
  'The impediment to action advances action. What stands in the way becomes the way.',
  'I act from principle, not from impulse.',
  'My worth does not depend on outcomes beyond my control.',
  'I return to equanimity. This has always been available to me.',
  'I do not pursue what I cannot have. I cultivate what I already possess.',
  'Loss reminds me of value. Difficulty reminds me of strength.',
  'I accept this moment completely, then work to improve what I can.',

  // ── Stoic: Present Moment & Attention ───────────────────
  'I do this one thing, now, with full attention.',
  'The present moment is the only place where life exists.',
  'I am not scattered across past regrets and future worries.',
  'Wherever I am, I choose to be fully there.',
  'My attention is my most valuable resource. I spend it wisely.',
  'I resist the pull of distraction and return to what matters.',
  'I do not rush through the moment I am in to reach the next one.',
  'Each task deserves the full weight of my presence.',
  'I notice where my mind goes, and I choose to bring it back.',

  // ── Stoic: Character & Virtue ───────────────────────────
  'I define myself by my actions, not my intentions.',
  'I act as if the person I want to become is already watching.',
  'Virtue practiced under pressure is virtue proven.',
  'I choose the harder right over the easier wrong.',
  'I do not need to be seen doing good in order to do it.',
  'Who I am when no one watches is who I actually am.',
  'Small acts of integrity compound into a life of integrity.',
  'I ask: what would a wise, courageous, and just person do here?',
  'My character is built in ordinary moments, not grand ones.',
  'I am honest, even when honesty is uncomfortable.',
  'I hold myself to a standard, not a mood.',

  // ── Stoic: Mortality & Urgency ───────────────────────────
  'I act today as if time is limited — because it is.',
  'Remembering that I will die makes me live more deliberately.',
  'I do not postpone what matters to a future I cannot guarantee.',
  'Urgency is not anxiety — it is respect for finite time.',
  'This day will not come again. I treat it accordingly.',
  'I do not waste the one life I have been given.',

  // ── Growth Mindset (Dweck) ──────────────────────────────
  'My abilities are not fixed — they grow with effort and practice.',
  'I am not yet where I want to be, and that is acceptable.',
  'Failure is not a verdict on my worth; it is data for my improvement.',
  'I replace "I can\'t do this" with "I can\'t do this yet."',
  'Struggle is evidence that I am learning, not evidence that I am failing.',
  'I measure progress against my past self, not against others.',
  'Criticism is information. I receive it calmly and use it well.',
  'The discomfort of growth is something I willingly accept.',
  'I seek challenge because comfort produces stagnation.',
  'Talent is a starting point. Effort is what determines the finish.',
  'I am curious about what I do not yet know.',
  'Each attempt, successful or not, makes the next attempt better.',
  'I do not fear looking foolish while learning something new.',
  'My brain changes and strengthens with every deliberate practice.',
  'I commit to mastery, not performance.',

  // ── Meaning & Purpose (Frankl) ──────────────────────────
  'I choose my attitude in any set of circumstances.',
  'Everything can be taken from me but my freedom to respond.',
  'When I know my why, I can bear almost any how.',
  'Meaning is not found — it is created through what I do and how I love.',
  'Suffering without meaning is unbearable. I give my struggles meaning.',
  'I do not ask what I want from life. I ask what life wants from me.',
  'I am responsible to something larger than my own comfort.',
  'I find dignity in work done well, no matter how small.',
  'Love is the only thing that persists when everything else is stripped away.',
  'I hold on to meaning, especially in difficulty.',

  // ── Resilience & Hardship ───────────────────────────────
  'I have survived hard things before. I will survive this.',
  'Hardship does not end me — it changes me in ways I may not yet understand.',
  'I do not need to feel ready. I need to begin.',
  'I keep going, not because it is easy, but because quitting costs more.',
  'Pressure is a privilege. It means I am doing something that matters.',
  'I rest when I need to. Resting is not quitting.',
  'I do not expect the path to be clear before I start walking it.',
  'The difficulty I face today is building the capacity I need tomorrow.',
  'I am not broken by what is hard. I am formed by it.',
  'I acknowledge pain without being consumed by it.',
  'I have more reserves than I currently believe.',
  'I act in spite of fear. Fear is information, not a command.',

  // ── Discipline & Habits (Aristotle / James Clear) ────────
  'I am not my goals — I am my daily habits.',
  'I do not rely on motivation. I rely on systems and commitment.',
  'Excellence is not an act but a habit. I build it daily.',
  'I do the work whether or not I feel like it.',
  'Small consistent actions outperform large sporadic efforts.',
  'I design my environment to support the person I want to become.',
  'I show up. That alone separates me from most.',
  'I do not break the chain. Each day builds on the last.',
  'Identity precedes behavior. I act as the person I am becoming.',
  'The 1% improvements are invisible today and transformative over years.',
  'I choose long-term gain over short-term comfort.',
  'I start before I am ready, adjust as I go.',
  'Mastery requires repetition far past the point of boredom.',

  // ── Honesty & Self-Knowledge ────────────────────────────
  'I see myself clearly, neither inflating nor diminishing my reality.',
  'Self-knowledge is the beginning of every kind of wisdom.',
  'I ask hard questions of myself and wait patiently for honest answers.',
  'I acknowledge my flaws so I can actually work on them.',
  'I do not confuse confidence with competence — in myself or others.',
  'I hold my beliefs loosely and update them when evidence demands.',
  'I am willing to be wrong. That is how I get things right.',
  'I resist self-deception, which is the most dangerous kind.',

  // ── Relationships & Presence ─────────────────────────────
  'I listen to understand, not to respond.',
  'The people who matter most deserve my full attention.',
  'I am generous with my time to those I love.',
  'I express gratitude to people directly and often.',
  'I do not assume I know what others are experiencing.',
  'I give others the benefit of the doubt before assuming bad intent.',
  'I apologize when I am wrong, quickly and without qualification.',
  'Strong relationships are built in ordinary moments, not grand gestures.',

  // ── Simplicity & Enough ──────────────────────────────────
  'I already have what I need for this moment.',
  'Wanting less is as powerful as having more.',
  'I do not need more things to have a rich life.',
  'Complexity is the enemy of execution. I simplify.',
  'A few things done deeply is better than many things done shallowly.',
  'Enough is a radical and liberating idea. I practice it.',
  'I subtract before I add. Clarity comes from removal.',
  'The essentials deserve my full energy. Everything else can wait.',

  // ── Equanimity & Emotional Regulation ───────────────────
  'I notice my emotions without being ruled by them.',
  'Anger is a signal, not an instruction.',
  'I pause before I react. A breath is enough to choose differently.',
  'I do not suppress feelings — I observe them and decide what to do.',
  'Anxiety often mistakes possibility for probability. I correct this.',
  'I am not my worst moment. Neither is anyone else.',
  'I can hold uncertainty without needing to resolve it immediately.',
  'Calm is a skill, and I am building it.',
  'I return to my breath. My body is always in the present.',
  'Even difficult emotions pass. I let them move through me.',

  // ── Courage & Action ─────────────────────────────────────
  'Courage is not the absence of fear — it is acting despite it.',
  'I do not wait for permission to pursue what matters.',
  'Inaction is also a choice, with its own consequences.',
  'I make the decision with the information I have, then adjust.',
  'I speak up when something important needs to be said.',
  'I take the first step. The rest becomes clearer from there.',
  'Done imperfectly is worth more than perfected in my head.',
  'I take risks proportionate to what I value.',
  'Regret for inaction outlasts regret for action. I choose to act.',
]
